In [30]:
import numpy as np
import pandas as pd

In [31]:
rolls = np.random.random_integers(1, 20, 10000000)
rolls2 = np.random.random_integers(1, 20, 10000000)
matrix = pd.DataFrame(rolls)

In [32]:
matrix['roll2'] = rolls2

In [33]:
matrix

          0  roll2
0        12     13
1         1      2
2        17      2
3        12      4
4        14      9
5        19      3
6        20      4
7         1     19
8         1     14
9         8     11
10       20     19
11        7      3
12       18     15
13        3     17
14       11     20
15       18     17
16       18     16
17       17     20
18        4      8
19       18     14
20        2     12
21        4     19
22       19      2
23        2      8
24       14      3
25        7     18
26        3     18
27       13     18
28        4     16
29       20      3
...      ..    ...
9999970  12     19
9999971   1      2
9999972   2     16
9999973   4     13
9999974   6      3
9999975   3     20
9999976  12     13
9999977  10      9
9999978  19      5
9999979  11     16
9999980   5      8
9999981   8     13
9999982   7      6
9999983  18      4
9999984   5     11
9999985   5     15
9999986  15     17
9999987   3     20
9999988  10     18
9999989  19     19
9999990   7     12
9999991   3     10
9999992  16     19
9999993  14      2
9999994   6     13
9999995   9      2
9999996   1     14
9999997  20     18
9999998  13     11
9999999   7      3

[10000000 rows x 2 columns]

In [34]:
matrix.columns = ['roll1', 'roll2']
matrix

         roll1  roll2
0           12     13
1            1      2
2           17      2
3           12      4
4           14      9
5           19      3
6           20      4
7            1     19
8            1     14
9            8     11
10          20     19
11           7      3
12          18     15
13           3     17
14          11     20
15          18     17
16          18     16
17          17     20
18           4      8
19          18     14
20           2     12
21           4     19
22          19      2
23           2      8
24          14      3
25           7     18
26           3     18
27          13     18
28           4     16
29          20      3
...        ...    ...
9999970     12     19
9999971      1      2
9999972      2     16
9999973      4     13
9999974      6      3
9999975      3     20
9999976     12     13
9999977     10      9
9999978     19      5
9999979     11     16
9999980      5      8
9999981      8     13
9999982      7      6
9999983     18      4
9999984      5     11
9999985      5     15
9999986     15     17
9999987      3     20
9999988     10     18
9999989     19     19
9999990      7     12
9999991      3     10
9999992     16     19
9999993     14      2
9999994      6     13
9999995      9      2
9999996      1     14
9999997     20     18
9999998     13     11
9999999      7      3

[10000000 rows x 2 columns]

In [37]:
%timeit matrix[(matrix['roll1'] == 19) | (matrix['roll1'] == 20) | (matrix['roll2'] == 19) | (matrix['roll2'] == 20) | \
       (matrix['roll1'] == matrix['roll2'])].count() / 10000000 * 100

1 loops, best of 3: 282 ms per loop